### ISSUE TITLE
How are these xx-rootfs.tar.xz files created?

### ISSUE THREAD

**Issue by mkinney** [oracle/ol-container-images#1]
I'm assuming there is a minimal kickstart file, then some scripts to create these files.

Is it documented the steps that are run to go from iso to xx-rootfs.tar.xz?

**Comment by Djelibeybi** [comment]
There is no kickstart file. The tarballs are created using a modified version of the `mkimage-yum.sh` script: https://github.com/moby/moby/blob/master/contrib/mkimage-yum.sh
