### ISSUE TITLE
YUM repo control file permissions

### ISSUE THREAD

**Issue by Marakai** [oracle/ol-container-images#2]
We are trying to build a new base image which has YUM pointing to our own repository servers. However we are unable to override /etc/yum.repos.d due to:

[p752644@ligsa774575 ncapi2docker]$ docker run -it --rm oraclelinux:7-slim bash
bash-4.2# ls -lR /etc/yum.repos.d
/etc/yum.repos.d:
total 8
-rw-rw-r--. 10 root root 6945 Nov 28 00:57 public-yum-ol7.repo
bash-4.2# rm -fr /etc/yum.repos.d/
rm: cannot remove '/etc/yum.repos.d/': Directory not empty
bash-4.2# ls -lR /etc/yum.repos.d
/etc/yum.repos.d:
ls: cannot access /etc/yum.repos.d/public-yum-ol7.repo: No such file or directory
total 0
?????????? ? ? ? ?            ? public-yum-ol7.repo
bash-4.2#

**Comment by Djelibeybi** [comment]
This looks like an issue with your deployment. Works fine for me:

```
$ docker run --rm -ti oraclelinux:7-slim /bin/bash
bash-4.2# ls -lR /etc/yum.repos.d/
/etc/yum.repos.d/:
total 8
-rw-rw-r-- 1 root root 6947 Sep 29 05:51 public-yum-ol7.repo
```

You'll need to review your Docker configuration and perhaps check SElinux.

**Comment by Marakai** [comment]
SELinux is permissive. Docker is CE 17.09. Strangely enough I can simply truncate the .repo file to zero - which I use as a work-around for now. I'll investigate what's different.

**Comment by Djelibeybi** [comment]
What is the output of `docker info` on this host?

**Comment by Marakai** [comment]
[p752644@ligsa774575 ncapi2docker]$ docker info
Containers: 35
 Running: 0
 Paused: 0
 Stopped: 35
Images: 571
Server Version: 17.09.0-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-693.5.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.781GiB
Name: ligsa774575.aur.national.com.au
ID: KFWX:OIQH:TCKJ:3MXN:ENSH:OQGN:BFHJ:VKGI:AFNX:OUVN:WUOQ:UUN3
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: http://proxy.example.com:80/b.com.au:10091/
No Proxy: localhost,127.0.0.0/8,repository.aur.national.com.au,10.0.0.0/8
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 repository.aur.national.com.au
 127.0.0.0/8
Registry Mirrors:
 https://repository.aur.national.com.au/
Live Restore Enabled: false

WARNING: overlay: the backing xfs filesystem is formatted without d_type support, which leads to incorrect behavior.
         Reformat the filesystem with ftype=1 to enable d_type support.
         Running without d_type support will not be supported in future releases.

**Comment by Djelibeybi** [comment]
I suspect this is your problem:

```
WARNING: overlay: the backing xfs filesystem is formatted without d_type support, which leads to incorrect behavior.
Reformat the filesystem with ftype=1 to enable d_type support.
Running without d_type support will not be supported in future releases.
```

You'll need to format your `/var/lib/docker` filesystem with `ftype=1` so that the backing store works properly with `overlay2`.

**Comment by Djelibeybi** [comment]
Note that Oracle Linux 7 Update 4 correctly formats the root filesystem with `ftype=1` during the installation process so that it can be used with Docker properly. Given that both Oracle Linux and CentOS are free to download, distribute, use and update, I would suggest switching to Oracle Linux 7 and our build of Docker to avoid this issue.

**Comment by Marakai** [comment]
I was afraid of that. I'm mimicking the hosts setup, which for reasons to long to list here also did not have the /v/l/d directory installed with ftype=1.

**Comment by Djelibeybi** [comment]
You'll have to fix the host as well. Otherwise, you'll run into all sorts of filesystem issues down the track.
